use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};
use sqlx::FromRow;
use uuid::Uuid;

#[derive(Debug, Clone, Serialize, Deserialize, FromRow)]
pub struct User {
    pub id: Uuid,
    pub email: String,
    pub name: String,
    pub created_at: DateTime<Utc>,
    pub updated_at: DateTime<Utc>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Farm {
    pub id: Uuid,
    pub user_id: Uuid,
    pub name: String,
    pub geometry: GeoPolygon,
    pub area_hectares: f64,
    pub crop_type: Option<CropType>,
    pub created_at: DateTime<Utc>,
    pub updated_at: DateTime<Utc>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct GeoPolygon {
    pub coordinates: Vec<Vec<[f64; 2]>>,
    pub crs: String,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "snake_case")]
pub enum CropType {
    Rice,
    Durian,
    Mango,
    Coconut,
    Shrimp,
    Other(String),
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SatelliteImage {
    pub id: Uuid,
    pub source: SatelliteSource,
    pub acquisition_date: DateTime<Utc>,
    pub cloud_cover_percentage: f32,
    pub geometry: GeoPolygon,
    pub file_path: String,
    pub bands: Vec<SpectralBand>,
    pub processed: bool,
    pub created_at: DateTime<Utc>,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "snake_case")]
pub enum SatelliteSource {
    Sentinel2,
    Sentinel1,
    Landsat8,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SpectralBand {
    pub name: String,
    pub wavelength_nm: Option<f32>,
    pub resolution_m: f32,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SpectralIndices {
    pub id: Uuid,
    pub image_id: Uuid,
    pub farm_id: Uuid,
    pub calculated_at: DateTime<Utc>,
    pub ndvi: Option<f32>,
    pub ndsi: Option<f32>,
    pub srvi: Option<f32>,
    pub red_edge_index: Option<f32>,
    pub mean_values: SpectralMeanValues,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
pub struct SpectralMeanValues {
    pub ndvi_mean: f32,
    pub ndvi_std: f32,
    pub ndsi_mean: f32,
    pub ndsi_std: f32,
    pub red_edge_mean: f32,
    pub red_edge_std: f32,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Alert {
    pub id: Uuid,
    pub farm_id: Uuid,
    pub alert_type: AlertType,
    pub severity: AlertSeverity,
    pub title: String,
    pub description: String,
    pub geometry: Option<GeoPolygon>,
    pub detected_at: DateTime<Utc>,
    pub acknowledged: bool,
    pub acknowledged_at: Option<DateTime<Utc>>,
    pub metadata: AlertMetadata,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "snake_case")]
pub enum AlertType {
    SalinityIntrusion,
    CropStress,
    Deforestation,
    AnomalyDetected,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Ord, PartialOrd, Eq)]
#[serde(rename_all = "snake_case")]
pub enum AlertSeverity {
    Low,
    Medium,
    High,
    Critical,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
pub struct AlertMetadata {
    pub ndsi_value: Option<f32>,
    pub ndsi_change: Option<f32>,
    pub red_edge_change: Option<f32>,
    pub intrusion_vector: Option<IntrusionVector>,
    pub affected_area_hectares: Option<f64>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct IntrusionVector {
    pub direction_degrees: f32,
    pub magnitude_meters: f32,
    pub velocity_m_per_day: f32,
    pub start_point: [f64; 2],
    pub end_point: [f64; 2],
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SegmentationResult {
    pub id: Uuid,
    pub image_id: Uuid,
    pub model_version: String,
    pub classes: Vec<SegmentedClass>,
    pub processed_at: DateTime<Utc>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SegmentedClass {
    pub class_id: u32,
    pub class_name: String,
    pub geometry: GeoPolygon,
    pub area_hectares: f64,
    pub confidence: f32,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Todo {
    pub id: Uuid,
    pub user_id: Uuid,
    pub farm_id: Option<Uuid>,
    pub title: String,
    pub description: Option<String>,
    pub priority: TodoPriority,
    pub due_date: Option<DateTime<Utc>>,
    pub completed: bool,
    pub completed_at: Option<DateTime<Utc>>,
    pub created_at: DateTime<Utc>,
    pub source: TodoSource,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "snake_case")]
pub enum TodoPriority {
    Low,
    Medium,
    High,
    Urgent,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "snake_case")]
pub enum TodoSource {
    Manual,
    AutoGenerated,
    Chatbot,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Report {
    pub id: Uuid,
    pub user_id: Uuid,
    pub farm_id: Uuid,
    pub report_type: ReportType,
    pub title: String,
    pub content: String,
    pub time_range_start: DateTime<Utc>,
    pub time_range_end: DateTime<Utc>,
    pub generated_at: DateTime<Utc>,
    pub file_path: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "snake_case")]
pub enum ReportType {
    Weekly,
    Monthly,
    Custom,
    Alert,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PeakValleyDetection {
    pub timestamp: DateTime<Utc>,
    pub index_type: SpectralIndexType,
    pub value: f32,
    pub detection_type: DetectionType,
    pub baseline_value: f32,
    pub deviation_percentage: f32,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "snake_case")]
pub enum SpectralIndexType {
    Ndvi,
    Ndsi,
    RedEdge,
    Srvi,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "snake_case")]
pub enum DetectionType {
    Peak,
    Valley,
    Normal,
}
